fixes needed to correctly inspect remote images
buildpacks/pack pull request #1057
Opened 2021-02-04 05:48 UTC by dwillist

Signed-off-by: dwillist <dthornton@vmware.com>

## Summary

Add support for running `pack inspect-image` on remote images. 

## Output

#### Before
remote images were not inspected, instead local image info was duplicated.

#### After
remote images are inspected!

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1034 
Requires buildpacks/imgutil#90 to be merged.

2021-02-09 18:03 UTC, dfreilich requested changes

2021-02-09 18:03 UTC, dfreilich commented on acceptance/os/variables_darwin.go
> +var PackBinaryExp = regexp.MustCompile(`pack-v\d+.\d+.\d+-macos\.`)
nit: Remove and rebase

2021-02-09 18:03 UTC, dfreilich commented on go.mod
> +
remove, and update imgutil

2021-02-09 18:03 UTC, dfreilich commented on inspect_image.go
> +
```suggestion
```

2021-03-03 00:21 UTC, dwillist commented
Recent commits on this branch also address the problems in #1095

2021-03-04 14:13 UTC, dfreilich approved these changes
Fantastic! Just small nit in comment

2021-03-04 14:13 UTC, dfreilich commented on acceptance/acceptance_test.go
> +							// TODO: remove this condition after pack 0.17.2 is released
```suggestion
							// TODO: remove this condition after pack 0.17.0 is released
```

2021-03-04 16:54 UTC, merged