Cleanup registry cache in tests
buildpacks/pack pull request #1235
Opened 2021-07-20 17:01 UTC by jkutner

Keep a reference to the registry cache dir, which can be used to cleanup in test. Fixes #1228

This only happens when we're testing with a an empty string (`""`) for the root of the registry cache, and the temp dir is actually created from within the production code (not the test code). Therefore, we need to keep a reference to the temp dir so it can be destroyed in `it.After`

## Summary

## Output

#### Before

```
$ go test -run TestRegistryCache ./...
$ git status
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        internal/registry/registry087316852/
```

#### After

```
$ go test -run TestRegistryCache ./...
$ git status
...
nothing to commit, working tree clean
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1228

2021-07-20 17:17 UTC, aemengo requested changes

2021-07-20 17:17 UTC, aemengo commented on internal/registry/registry_cache_test.go
> +				h.AssertNil(t, os.RemoveAll(filepath.Join(registryCache.Root, registryCache.RegistryDir)))
```suggestion
				h.AssertNil(t, os.RemoveAll(registryCache.RegistryDir))
```

I hate to be persnickety, but the `.RegistryDir` is already an absolute path. Having the `.Join` there is just a _tad_ more confusing. Enough for me to mention it.

2021-07-20 17:17 UTC, aemengo commented on internal/registry/registry_cache_test.go
> +				h.AssertNil(t, os.RemoveAll(filepath.Join(registryCache.Root, registryCache.RegistryDir)))
```suggestion
				h.AssertNil(t, os.RemoveAll(registryCache.RegistryDir))
```

I hate to be persnickety, but the `.RegistryDir` is already an absolute path. Having the `.Join` there is just a _tad_ more confusing. Enough for me to mention it.

2021-07-20 21:06 UTC, aemengo approved these changes

2021-07-21 02:08 UTC, jromero approved these changes

2021-07-21 02:08 UTC, merged